### ISSUE TITLE
CSV GET SIZE command documentation miss8ng

### ISSUE THREAD

**Issue by knw257** [SAMMISolutions/docs#117]
There is a command in LB2 called CSV GET SIZE which does not appear to be documented. While the functionality seems obvious based on the name, I'm not sure it's working as I would expect. Could we get the specific functionality added to documentation?

**Comment by christinna9031** [comment]
Hi, you're correct that some stuff is still missing :)  You can edit the page yourself if you'd like! See here:  https://lioranboard.ca/docs2/getting-started/community#editapage
