### ISSUE TITLE
Add demo screenshots to home-page

### ISSUE THREAD

**Issue by Julian-O** [SAMMISolutions/docs#125]
[I am a streamer, with coding experience, but no prior knowledge of what LioranBoard is. This is a newbie's perspective.]

The LioranBoard.ca home page has no screenshots.

If you look at the [LioranBoard 2 Stream Deck](https://steprimo.com/android/us/app/lioranboard.ca.lioranboard.streamdeck/LioranBoard-2-Stream-Deck/) page you can see an actual deck with buttons. 

This is a great way to get a quick context and understanding whether this tool is useful.

Suggestion: Include a demo button deck.

Suggestion: Include a page that shows multiple decks being selectable.

Suggestion: Perhaps include a config page showing the flexibility of the rules (this might be a bit overwhelming before the concepts are explained, so it may be less useful.)

**Comment by SAMMISolutions** [comment]
Thanks Julian, it's been on the road map for some time now. We will be adding screenshots and short videos to the main page as we rebrand to SAMMI.
