### ISSUE TITLE
Add more context to home page to explain what the project does.

### ISSUE THREAD

**Issue by Julian-O** [SAMMISolutions/docs#126]
[I am a streamer, with coding experience, but no prior knowledge of what LioranBoard is. This is a newbie's perspective.]

The home pages says:

> LioranBoard 2 is a fully customizable Stream Deck that lets your Twitch and YouTube Live audience control and interact with your stream.

I read that, and was still not sure if this was:

* A competitor to [FreeDeck](https://freeyourstream.com/) - an open source *hardware* deck.
* An open source alternative to the standard code that comes with an Elgato Stream Deck ([example](https://www.reddit.com/r/elgato/comments/tcjzte/made_an_opensource_alternative_to_the_official/))
* An android app that has buttons that can directly drive OBS.
* What it actually is.

Include a description that places LioranBoard in context.

Here is a suggestion:

> LioranBoard 2 is a fully customizable software-based Stream Deck that lets you (and your Twitch and YouTube Live audience) quickly control and interact with your stream. You can use simple or complex sequences that talk to OBS, chat, (*and whatever; I don't know this project's scope yet*). It runs on Windows (or Windows compatible) machines. 
>
> Actions can be triggered by on-screen buttons, apps on Android (*and whatever*), chat, redemptions, (*and whatever*)

**Comment by SAMMISolutions** [comment]
Thanks Julian, it's been on the road map for some time now. We will be adding screenshots and short videos to the main page as we rebrand to SAMMI.
